In [2]:

import pandas as pd

# Selected rows transcribed from Table 2 of the published trial paper.
# Values are group summaries; age and comorbidity are mean ± SD in the paper.
table2_excerpt = pd.DataFrame({
    "Measure": [
        "Age (mean years)",
        "Male sex (%)",
        "White race (%)",
        "Black race (%)",
        "Charlson comorbidity index (mean)"
    ],
    "CONCERN intervention": [
        "62.62 ± 17.56",
        "48.62",
        "57.30",
        "14.77",
        "3.11 ± 3.16"
    ],
    "Usual care": [
        "63.67 ± 17.10",
        "50.11",
        "58.41",
        "15.16",
        "3.51 ± 3.34"
    ]
})

table2_excerpt
# Basic descriptive checks
print("Rows and columns:", table2_excerpt.shape)
print("\\nColumn names:")
print(table2_excerpt.columns.tolist())

print("\\nData types and non-null counts:")
table2_excerpt.info()

print("\\nFirst rows:")
display(table2_excerpt.head())

print("\\nMissing values per column:")
display(table2_excerpt.isna().sum())

Rows and columns: (5, 3)
\nColumn names:
['Measure', 'CONCERN intervention', 'Usual care']
\nData types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Measure               5 non-null      object
 1   CONCERN intervention  5 non-null      object
 2   Usual care            5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes
\nFirst rows:

                             Measure CONCERN intervention     Usual care
0                   Age (mean years)        62.62 ± 17.56  63.67 ± 17.10
1                       Male sex (%)                48.62          50.11
2                     White race (%)                57.30          58.41
3                     Black race (%)                14.77          15.16
4  Charlson comorbidity index (mean)          3.11 ± 3.16    3.51 ± 3.34

\nMissing values per column:

Measure                 0
CONCERN intervention    0
Usual care              0
dtype: int64

# Data Analysis Case Study: AI Analysis of Nurses’ Documentation

**Case:** CONCERN Early Warning System  
**Research:** Rossetti et al., *Nature Medicine* (published online 2 April 2025)

This notebook uses a small excerpt transcribed from **Table 2** of the published trial paper. These are **aggregate summary statistics**, not patient-level records and not the model’s raw input data.

**Research source:** https://www.nature.com/articles/s41591-025-03609-7  
**Accessible full text:** https://pmc.ncbi.nlm.nih.gov/articles/PMC11177900/
## Step 1 — Find a real-world case

The CONCERN Early Warning System uses machine learning to analyze patterns in nurses’ electronic health-record documentation and surveillance activity. These patterns can act as signals of clinical concern and help flag hospitalized patients who may be deteriorating.

The system was evaluated in a one-year, multisite, cluster-randomized trial across 74 clinical units at two U.S. health systems, including 60,893 hospital encounters.

## Step 2 — Examine the data, methods, and outcomes

The algorithm analyzes real-time nursing surveillance documentation patterns, such as changes in the frequency or type of assessments and interventions. It generates a risk score for the clinical team (low, increased, high) to support clinical judgment.

Below is a small excerpt from the descriptive Table 2: Characteristics of Patients with Hospital Encounters During the Trial. It compares the intervention group with usual care. The table is an example of the published study data, not a downloadable row-level dataset.

In [3]:
import pandas as pd

# Selected rows transcribed from Table 2 of the published trial paper.
# Values are group summaries; age and comorbidity are mean ± SD in the paper.
table2_excerpt = pd.DataFrame({
    "Measure": [
        "Age (mean years)",
        "Male sex (%)",
        "White race (%)",
        "Black race (%)",
        "Charlson comorbidity index (mean)"
    ],
    "CONCERN intervention": [
        "62.62 ± 17.56",
        "48.62",
        "57.30",
        "14.77",
        "3.11 ± 3.16"
    ],
    "Usual care": [
        "63.67 ± 17.10",
        "50.11",
        "58.41",
        "15.16",
        "3.51 ± 3.34"
    ]
})

table2_excerpt
# Basic descriptive checks
print("Rows and columns:", table2_excerpt.shape)
print("\\nColumn names:")
print(table2_excerpt.columns.tolist())

print("\\nData types and non-null counts:")
table2_excerpt.info()

print("\\nFirst rows:")
display(table2_excerpt.head())

print("\\nMissing values per column:")
display(table2_excerpt.isna().sum())

Rows and columns: (5, 3)
\nColumn names:
['Measure', 'CONCERN intervention', 'Usual care']
\nData types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Measure               5 non-null      object
 1   CONCERN intervention  5 non-null      object
 2   Usual care            5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes
\nFirst rows:

                             Measure CONCERN intervention     Usual care
0                   Age (mean years)        62.62 ± 17.56  63.67 ± 17.10
1                       Male sex (%)                48.62          50.11
2                     White race (%)                57.30          58.41
3                     Black race (%)                14.77          15.16
4  Charlson comorbidity index (mean)          3.11 ± 3.16    3.51 ± 3.34

\nMissing values per column:

Measure                 0
CONCERN intervention    0
Usual care              0
dtype: int64

**How to interpret this excerpt:** the two groups have broadly similar values for these selected baseline characteristics. That helps describe the trial groups.

And here is the actual comparison summary of the two groups as provided in the paper:

In [4]:
import pandas as pd

data = {
    "Outcome": [
        "In-hospital deaths",
        "Length of stay (days)",
        "Sepsis cases",
        "Unexpected ICU transfers"
    ],
    "CONCERN system": [
        181,
        6.6,
        1461,
        505
    ],
    "Usual care": [
        265,
        7.2,
        1578,
        377
    ],
    "Adjusted difference (%)": [
        -35.6,
        -11.2,
        -7.5,
        24.9
    ]
}

df = pd.DataFrame(data)
display(df)

,Outcome,CONCERN system,Usual care,Adjusted difference (%)
0,In-hospital deaths,181.0,265.0,-35.6
1,Length of stay (days),6.6,7.2,-11.2
2,Sepsis cases,1461.0,1578.0,-7.5
3,Unexpected ICU transfers,505.0,377.0,24.9

**Deaths**: The adjusted hazard ratio was 0.644, indicating a 35.6% lower instantaneous risk of in-hospital death in the intervention group.
**Length of stay**: The reported unadjusted averages were 6.6 versus 7.2 days, although the adjusted analysis estimated an 11.2% reduction.
**Sepsis**: The adjusted hazard ratio was 0.925, indicating a 7.5% lower instantaneous risk.
**Unexpected ICU transfers**: These increased, potentially reflecting earlier recognition and escalation of care. **This is not automatically a worse outcome.**
The mortality and length-of-stay findings were statistically significant; the sepsis result was also statistically significant, with a smaller effect.

PubMed
+1

## Step 3 — Consider the impact of data analysis

Without analyzing documentation patterns, signs of concern recorded through routine nursing activity could be harder for the wider care team to recognize consistently. The early-warning score makes these patterns more visible and may prompt reassessment or escalation of care. The trial found an association between the intervention and improved outcomes, but an algorithm does not independently make clinical decisions, and results depend on documentation quality and clinical response.
## Step 4 —Finding summary

The CONCERN case shows how data analysis can extract useful signals from everyday clinical records, not just from vital-sign measurements. Machine learning converted patterns in nursing surveillance documentation into a real-time warning for clinical teams. In a randomized trial of 60,893 hospital encounters, the intervention group had a 35.6% lower adjusted instantaneous risk of in-hospital death, a 7.5% lower risk of sepsis, and an 11.2% shorter length of stay compared with usual care. The study also reported more unanticipated ICU transfers, emphasizing that earlier recognition may lead to escalation. The system is best understood as decision support that complements nurses’ expertise, not as a replacement for clinical judgment.

### References
1. Rossetti, S. C., et al. (2025). “Real-time surveillance system for patient deterioration: a pragmatic cluster-randomized controlled trial.” *Nature Medicine*, 31, 1895–1902. https://doi.org/10.1038/s41591-025-03609-7  
2. Full text: https://pmc.ncbi.nlm.nih.gov/articles/PMC11177900/